import json
import os
from datetime import datetime

def generate_html_report(report_json_path, output_dir="reports"):
    os.makedirs(output_dir, exist_ok=True)

    with open(report_json_path, "r") as f:
        report = json.load(f)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Automated EDA Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background: #f4f6f9;
            margin: 0;
            padding: 0;
        }}

        .container {{
            max-width: 1000px;
            margin: auto;
            padding: 30px;
        }}

        h1 {{
            text-align: center;
            color: #2c3e50;
        }}

        .timestamp {{
            text-align: center;
            color: #777;
            margin-bottom: 30px;
        }}

        .card {{
            background: white;
            border-radius: 10px;
            padding: 20px;
            margin-bottom: 25px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.08);
        }}

        .card h2 {{
            color: #34495e;
            border-bottom: 2px solid #eee;
            padding-bottom: 8px;
        }}

        ul {{
            padding-left: 20px;
        }}

        li {{
            margin: 6px 0;
        }}

        .badge {{
            display: inline-block;
            background: #3498db;
            color: white;
            padding: 4px 10px;
            border-radius: 20px;
            font-size: 12px;
            margin-right: 6px;
        }}

        footer {{
            text-align: center;
            color: #888;
            margin-top: 40px;
            font-size: 13px;
        }}
    </style>
</head>

<body>
    <div class="container">
        <h1>📊 Automated EDA Report</h1>
        <div class="timestamp">Generated on: {timestamp}</div>

        <div class="card">
            <h2>🔍 Dataset Overview</h2>
            <p><b>Shape:</b> {report["dataset_shape"]}</p>
            <p><b>Columns:</b></p>
            <ul>
                {''.join(f"<li><span class='badge'>{col}</span></li>" for col in report["columns"])}
            </ul>
        </div>

        <div class="card">
            <h2>🚨 Anomaly Detection</h2>
            <ul>
                {''.join(f"<li><b>{k}</b>: {v}</li>" for k, v in report["anomalies"].items())}
            </ul>
        </div>

        <div class="card">
            <h2>🧠 Feature Recommendations</h2>
            <ul>
                {''.join(f"<li>{rec}</li>" for rec in report["feature_recommendations"])}
            </ul>
        </div>

        <footer>
            Generated by Automated EDA Agent 🚀
        </footer>
    </div>
</body>
</html>
"""

    output_path = os.path.join(output_dir, "eda_report.html")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"📄 HTML Report saved to: {output_path}")